# Generated by Django 3.2.7 on 2021-11-08 08:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SenseTree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curated_sense', models.TextField(default='')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('word_root', models.TextField(default='')),
                ('curated_by', models.TextField(default='')),
                ('reviewed_by', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FileField(upload_to='')),
                ('location', models.TextField(blank=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.TextField()),
                ('utype', models.TextField(default='omen')),
                ('ustatus', models.TextField(default='success')),
                ('report', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sense_uri', models.TextField(default='')),
                ('sense_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.sensetree')),
            ],
        ),
    ]
