# Generated by Django 3.2.7 on 2021-11-08 08:57

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=100, unique=True)),
                ('animal', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=100, null=True)),
                ('proofreader', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('ctime', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('tei', models.TextField(blank=True, default='', null=True)),
                ('introduction', ckeditor.fields.RichTextField(blank=True, default='Page under construction', null=True)),
                ('upload', models.ManyToManyField(to='curator.Upload')),
            ],
        ),
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('xml_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lemma_idx', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Omen',
            fields=[
                ('xml_id', models.CharField(max_length=100, unique=True)),
                ('omen_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('omen_num', models.CharField(max_length=100)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.chapter')),
                ('upload', models.ManyToManyField(to='curator.Upload')),
            ],
        ),
        migrations.CreateModel(
            name='Reconstruction',
            fields=[
                ('xml_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('omen', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.omen')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xml_id', models.CharField(max_length=100, unique=True)),
                ('segment_type', models.CharField(choices=[('PROTASIS', 'Protasis'), ('APODOSIS', 'Apodosis')], default='PROTASIS', max_length=9)),
                ('omen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.omen')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('museum_numbers', models.TextField(blank=True, null=True)),
                ('provenance', models.CharField(blank=True, max_length=100, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('state_publication', models.TextField(blank=True, null=True)),
                ('state_preservation', models.TextField(blank=True, null=True)),
                ('manuscript_type', models.TextField(blank=True, null=True)),
                ('tablets_attested', models.TextField(blank=True, null=True)),
                ('omens_attested', models.TextField(blank=True, null=True)),
                ('cdli_number', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transliteration',
            fields=[
                ('xml_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lemma', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.lemma')),
                ('reconstruction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.reconstruction')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('xml_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('translation_txt', models.CharField(default='', max_length=1000)),
                ('lang', models.CharField(choices=[('en', 'ENGLISH'), ('dt', 'GERMAN'), ('de', 'GERMAN')], default='en', max_length=2)),
                ('reconstruction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.reconstruction')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.segment')),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('xml_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('lemma', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.lemma')),
                ('reconstruction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='omens.reconstruction')),
            ],
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_name', models.CharField(max_length=100, unique=True)),
                ('position', models.IntegerField(default=0)),
                ('omen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.omen')),
            ],
        ),
        migrations.AddField(
            model_name='reconstruction',
            name='witness',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='omens.witness'),
        ),
        migrations.AddField(
            model_name='omen',
            name='witness',
            field=models.ManyToManyField(to='omens.Witness'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='omen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.omen'),
        ),
        migrations.AddField(
            model_name='lemma',
            name='segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.segment'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='witness',
            field=models.ManyToManyField(to='omens.Witness'),
        ),
    ]
