# Generated by Django 3.2.7 on 2021-11-12 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhilComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('omen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omens.omen')),
            ],
        ),
    ]
