# Generated by Django 3.2.7 on 2021-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omens', '0002_philcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='omen',
            name='tei_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
