# Generated by Django 3.2.7 on 2021-11-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omens', '0003_omen_tei_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='tei',
        ),
    ]
