# Generated by Django 3.2.7 on 2022-01-09 11:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omens', '0004_remove_chapter_tei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philcomment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, default='No comment available', null=True),
        ),
    ]
