# Generated by Django 3.2.7 on 2022-01-09 11:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omens', '0005_alter_philcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='philcomment',
            name='comment',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
